
server:
  port: 8200
 
 
spring:
  datasource:
    username: root
    password: hit1160300919
    url: jdbc:mysql://localhost:3319/smartbuy?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.hit.sb.cart.model
 
#showSql
logging:
  level:
    com.hit.sb.mapper : debug
